--1.1
SELECT DISTINCT COMPANY 
FROM MANUFACTURER 
ORDER BY COMPANY 

--1.2
SELECT COUNT(DISTINCT COMPANY)
FROM MANUFACTURER

--1.3
SELECT DISTINCT WARE
FROM CATEGORY 
WHERE CLASS = 'Food'

--1.4
SELECT DISTINCT COMPANY FROM MANUFACTURER 
WHERE COMPANY LIKE 'A%' OR COMPANY LIKE 'B%'
ORDER BY COMPANY  

--1.5
SELECT DISTINCT WARE
FROM PRODUCT
WHERE WARE NOT IN (SELECT WARE FROM MATERIAL)

--1.6
SELECT DISTINCT WARE FROM CATEGORY
WHERE WARE NOT IN (SELECT WARE FROM PRODUCT)     --1.5 & 1.6: can use EXPECT too

--1.7
SELECT DISTINCT WARE FROM MATERIAL
WHERE WARE IN (SELECT WARE FROM PRODUCT)    --also INTERSECT

--1.8
SELECT MIN(PRICE), MAX(PRICE)    --also UNION
FROM PRODUCT 

--1.9
SELECT ROUND(AVG(PRICE))
FROM PRODUCT
WHERE WARE = 'Meat'

