--2.1
--SELECT DISTINCT MANUFACTURER.COMPANY, PRODUCT.WARE
--FROM MANUFACTURER, PRODUCT
--WHERE MANUFACTURER.RECIPE_ID=PRODUCT.RECIPE_ID 
--AND WARE = 'Drinking water'
--ORDER BY COMPANY ASC;

--2.2
SELECT DISTINCT PRODUCT.WARE
FROM PRODUCT
INTERSECT
SELECT DISTINCT CATEGORY.WARE
FROM CATEGORY
WHERE CATEGORY.CLASS = 'Mineral'
ORDER BY PRODUCT.WARE ASC