--2.1
SELECT DISTINCT MANUFACTURER.COMPANY, PRODUCT.WARE
FROM MANUFACTURER, PRODUCT
WHERE MANUFACTURER.RECIPE_ID=PRODUCT.RECIPE_ID 
AND WARE = 'Drinking water'
ORDER BY COMPANY ASC;

--2.3
SELECT DISTINCT PRODUCT.WARE FROM PRODUCT
INTERSECT
SELECT CATEGORY.WARE FROM CATEGORY
WHERE CATEGORY.CLASS = 'Mineral'
ORDER BY PRODUCT.WARE ASC

--3.1
SELECT DISTINCT WARE, MAX(PRICE), MIN(PRICE)
FROM PRODUCT
GROUP BY WARE;
